/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.justaddhippopotamus.ghr;

import com.justaddhippopotamus.ghr.server.Logger;
import com.justaddhippopotamus.ghr.server.Server;
import com.justaddhippopotamus.ghr.server.commands.ServerCommands;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class App {
    public static final String fileDir = "src/main/resources";

    public static void printLicense() {
        try {
            System.out.println(new String(getInputStreamFor("/LICENSE").readAllBytes(),Server.CHARSET));
        } catch (IOException e) {
            System.out.println("License file missing...bombing.");
            throw new RuntimeException(e);
        }
    }
    public static void printHelp() {
        System.out.println("Command Line Arguments:");
        System.out.println("    --port <portnum> (default is 6379)");
        System.out.println("    --file <dbfilename> (by default it is dbio.respdb");
        System.out.println("    --memoryOnly  (No saving or reading a db..");
        System.out.println("    --workers <number> (Number of worker threads, default 5)");
        System.out.println("    --license (prints the license)");
        System.out.println("    --help/-?/-h (This help)");
        System.out.println("    --password <password> (Default is none)");
        System.out.println("    --verbose (Verbose operation...spammy) (Adds INFO for all commands and sets default");
        System.out.println("                                            default logging level to INFO");
        System.out.println("    --logFilter <class> <level> (Level is DISABLE, TRACE, INFO, WARN, ERROR, EXCEPTION");
        System.out.println("    --logLevel <level> (Default log level, default is INFO)");
        System.out.println("    --noBanner    (Do not print banner.)");
        System.out.println();
        System.out.println("Go Horse Race is a java implementation of redis. Lua included not lua functions");
        System.out.println("but EVAL and EVALSHA are supported. (Using LuaJ, which is apparently lua 5.2)");
        System.out.println("Lua is somewhat sandboxed, but it is lua in java so there might be a way to make");
        System.out.println("write and read from the local file system.");
        System.out.println();
        System.out.println("GEO,PX,TDIGEST,TOPK,FT,CF,CMS,X commands not supported but they do return a");
        System.out.println("nice error message saying that they are not supported. Adding them is left as an");
        System.out.println("exercise for the listener.");
        System.out.println("");
        System.out.println("To make it behave just like redis, set number of workers to 1.");
    }

    public static void printBanner() {
        System.out.println("Go Horse Race db.                                                 ,--,");
        System.out.println("A somewhat complete 7.ish redis implementation.             _ ___/ /\\|");
        System.out.println("If this is somehow in production, just stop right now.     ;( )__, )");
        System.out.println("Read the license.                                         ; //   '--;");
        System.out.println("                                                            \\     |");
        System.out.println("                                                             ^    ^");
    }
    public static void main(String[] args) {
        running = true;

        ArrayList<String> argsList = new ArrayList<>();
        for( String s : args ) {
            argsList.add(s);
        }

        while( !argsList.isEmpty() ) {
            String currentArg = argsList.remove(0);
            switch(currentArg) {
                case "--logLevel":
                    String logLevel = argsList.remove(0);
                    Logger.setDefaultLogLevel(logLevel);
                    break;
                case "--logFilter":
                    String logWhat = argsList.remove(0);
                    String logFilter = argsList.remove(0);
                    Logger.setLogLevelFor(logWhat, logFilter);
                    break;
                case "--password":
                    password = argsList.remove(0);
                    break;
                case "--port":
                    port = Integer.parseInt(argsList.remove(0));
                    break;
                case "--file":
                    dbFile = currentArg;
                    break;
                case "--help":
                case "-?":
                case "-h":
                    printHelp();
                    System.exit(0);
                    return;
                case "-v":
                case "--verbose":
                    verbose = true;
                    Logger.setDefaultLogLevel(Logger.LogLevel.LOG_INFO);
                    break;
                case "--workers":
                    numWorkers = Integer.parseInt(argsList.remove(0));
                    break;
                case "--license":
                    printLicense();
                    System.exit(0);
                    return;
                case "--memoryOnly":
                    dbFile = null;
                    break;
                case "--noBanner":
                    printBanner = false;
                    break;
                default:
                    printBanner();
                    printHelp();
                    System.exit(-1);
                    return;
            }
        }
        if( printBanner ) printBanner();


        Server newServer = new Server(dbFile, port, password, numWorkers);
        Server.verbose = verbose;
        newServer.goDogGo();

        Runtime.getRuntime().addShutdownHook( new Thread() {
            @Override
            public void run() {
                newServer.stopIfNecessary();
                while( !newServer.mainLoopDone ) {
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                    }
                }
            }
        });

        while( !newServer.mainLoopDone ) {
            try {
                Thread.sleep(500);
            } catch (java.lang.InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }
        System.exit(0);
    }

    public static boolean printBanner = true;
    public static boolean verbose = false;
    public static boolean running = false;
    public static boolean killing = false;

    public static int port = 6379;
    public static int numWorkers = 1;
    public static String password = null;
    public static String dbFile = "dbio.respdb";

    public static InputStream getInputStreamFor(String resourcePath) {
        InputStream is = ServerCommands.class.getResourceAsStream(resourcePath);
        if (is == null) {
            try {
                is = new FileInputStream(fileDir + resourcePath);
            } catch (Exception e) {
            }
        }
        return is;
    }
}
